### ISSUE TITLE
Unable to integrate index.html

### ISSUE THREAD

**Issue by kimhongzhang323** [kimhongzhang323/Student-Portal-with-AI-#13]
### Description
I am encountering an error when trying to render the `index.html` template in my Django project. The error message is:

```
django.template.exceptions.TemplateDoesNotExist: index.html
```

This error occurs when I try to visit the homepage view which should render the `index.html` template.

### Steps Taken
1. **Template Directory Check**:
   - I confirmed that the `index.html` file is located in the `templates` directory at the following path:
     ```
     C:\Users\kimho\OneDrive\Documents\GitHub\Student-Portal-with-AI-\templates\index.html
     ```

2. **Settings.py Configuration**:
   - I checked the `DIRS` setting in `TEMPLATES` inside `settings.py`, ensuring it points to the correct templates folder:
     ```python
     TEMPLATES = [
         {
             'BACKEND': 'django.template.backends.django.DjangoTemplates',
             'DIRS': [
                 BASE_DIR / "templates",
             ],
             'APP_DIRS': True,
         }
     ]
     ```
   
3. **BASE_DIR Check**:
   - I verified that the `BASE_DIR` is properly defined in `settings.py`:
     ```python
     BASE_DIR = Path(__file__).resolve().parent.parent
     ```

4. **App Configuration**:
   - I confirmed that my app (`myapp`) is listed in the `INSTALLED_APPS` in `settings.py`:
     ```python
     INSTALLED_APPS = [
         'myapp',
     ]
     ```

5. **Template Path Usage**:
   - In the `views.py`, I used the correct template path in the `render` function:
     ```python
     def homepage(request):
         return render(request, 'index.html')
     ```

6. **Restarted Development Server**:
   - I restarted the Django development server to clear any potential caching issues.

### Expected Behavior
The expected behavior is for the `index.html` template to be rendered when accessing the homepage.

### Actual Behavior
Instead of rendering the `index.html` template, I am encountering the following error:
```
django.template.exceptions.TemplateDoesNotExist: index.html
```

### Conclusion
The template file `index.html` exists in the correct location, and I have followed all the necessary steps to configure Django to find the template. However, the template is still not being rendered, and the error persists.

---

###Refrence
![image](https://github.com/user-attachments/assets/92355cbb-adc8-4b5f-b03d-6d2ce5c48c16)

**Comment by JaxChoong** [comment]
Notes:
**WE ARE NOT USING DJANGO TO SERVE PAGES/HTML**
**DJANGO IS ONLY USES TO SERVE DATA/JSON**
- all routes should only return json

Fixes:
1. Removed the rendering of index.html in the index route
2.
